### ISSUE TITLE
Link broken in documentation

### ISSUE THREAD

**Issue by rubix1138** [MacHu-GWU/uszipcode-project#1]
On your documentation page, http://www.wbh-doc.com.s3.amazonaws.com/uszipcode/index.html, in the first "Basic Search" section, you have a line that reads:

    For all available zipcode attributes, click here.

The link for "click here" is file:///C:/Users/shu/Documents/PythonWorkSpace/py3/py33_projects/uszipcode-project/build/html/uszipcode/searchengine.html#uszipcode.searchengine.Zipcode

Can you upload this page to your site, so I can see the full attribute list?

**Comment by MacHu-GWU** [comment]
http://www.wbh-doc.com.s3.amazonaws.com/uszipcode/uszipcode/searchengine.html#uszipcode.searchengine.Zipcode

Sorry, the link should be. I 'll correct it soon
