### ISSUE TITLE
Missing longitude & latitude for Toledo, OH 43660

### ISSUE THREAD

**Issue by harrymattison** [MacHu-GWU/uszipcode-project#15]
Thanks for this good tool. Please add the longitude and latitude data for Toledo, OH.

by_zipcode(43660)

43660
SimpleZipcode(zipcode='43660', zipcode_type='Unique', major_city='Toledo', post_office_city=None, common_city_list=['Toledo'], county='Lucas County', state='OH', lat=None, lng=None, timezone=None, radius_in_miles=None, area_code_list=['419'], population=None, population_density=None, land_area_in_sqmi=None, water_area_in_sqmi=None, housing_units=None, occupied_housing_units=None, median_home_value=None, median_household_income=None, bounds_west=None, bounds_east=None, bounds_north=None, bounds_south=None)

**Comment by MacHu-GWU** [comment]
I am really sorry about that. since 43660 is not a standard zipcode, it is an unique zipcode for specific address. The lat lng for 43660 is this: 41.65, -83.54.

It is a little bit hard to update the database very frequently.

**Comment by RafaRafa** [comment]
Similar issue:

SimpleZipcode(zipcode='52771', zipcode_type='Standard', major_city='Teeds Grove', post_office_city=None, common_city_list=['Teeds Grove', 'Clinton'], county='Clinton County', state='IA', lat=None, lng=None, timezone=None, radius_in_miles=None, area_code_list=['563'], population=None, population_density=None, land_area_in_sqmi=None, water_area_in_sqmi=None, housing_units=None, occupied_housing_units=None, median_home_value=None, median_household_income=None, bounds_west=None, bounds_east=None, bounds_north=None, bounds_south=None)
