### ISSUE TITLE
Change database location

### ISSUE THREAD

**Issue by jkruszynski** [MacHu-GWU/uszipcode-project#16]
Is there an easy way to change the database location? Unable to get this working in AWS because the db file is located in a different directory.

**Comment by MacHu-GWU** [comment]
Now you can't. Are you trying to use AWS Lambda or EC2 instance? The idea solution is to upload the sqlite3 database 's data to AWS RDS, and connect the zipcode search engine to it.

It is a good idea though

**Comment by MacHu-GWU** [comment]
@jkruszynski I am adding an option to allow you custom database location in your app.

**Comment by MacHu-GWU** [comment]
@jkruszynski I just released 0.2.4, now you can specify the directory you want to download the db file to. By default it is still ``$HOME/.uszipcode``
