### ISSUE TITLE
Missing someting in manual?

### ISSUE THREAD

**Issue by altair0319** [MacHu-GWU/uszipcode-project#17]
>>> from uszipcode import Zipcode                                            
 Search zipcode within 30 miles, ordered from closest to farthest
>>> result = search.by_coordinates(39.122229, -77.133578, radius=30, returns=5)
>>> len(res) # by default 5 results returned
5

What does search stand for?

Thanks

**Comment by MacHu-GWU** [comment]
plz take a look at https://uszipcode.readthedocs.io/?badge=latest#example-usage, 
the first step using this is

```python
>>> from uszipcode import SearchEngine
>>> search = SearchEngine(simple_zipcode=False)
```
