### ISSUE TITLE
Radius Calculation

### ISSUE THREAD

**Issue by veryxcit** [MacHu-GWU/uszipcode-project#2]
Hey there has to be a bug with the by_coordinate method on certian lat,lng calculations. 
Try it with Lat 42.3612999 Long -88.0899304 (which are the coordinates pulled for zipcode 60073).

I came across this while looking for a 30 mile radius search for zipcodes based on 60073.

**Comment by MacHu-GWU** [comment]
Could you post your code with this bug to here please? Thank you.

**Comment by veryxcit** [comment]
`def bug(zip):

    search = ZipcodeSearchEngine()
    zipcode = search.by_zipcode(zip)
    print(zipcode)

    res = search.by_coordinate(zipcode.Latitude, zipcode.Longitude, radius=20, returns=0)
    for r in res:
        print(r.Zipcode)

bug(20855) # try zip 20855
bug(60073) # try zip 60073`

**Comment by veryxcit** [comment]
```
def bug(zip):

    search = ZipcodeSearchEngine()
    zipcode = search.by_zipcode(zip)
    print(zipcode)

    res = search.by_coordinate(zipcode.Latitude, zipcode.Longitude, radius=20, returns=0)
    for r in res:
        print(r.Zipcode)

bug(20855) # try zip 20855
bug(60073) # try zip 60073
```

Sorry I couldn't markdown the code earlier you probably got a bunch of notifications :) Anyway when trying to pull by zipcode 60073, there is nothing, no results. And I think the bug is all math ...

**Comment by MacHu-GWU** [comment]
How about try ``pip install --upgrade uszipcode``

I dont know why, the following code does gives me returns:

```
from uszipcode.searchengine import ZipcodeSearchEngine

search = ZipcodeSearchEngine()
z = search.by_zipcode("60073")
print(z)
```

gives me:

```
{
    "City": "Round Lake",
    "Density": 2926.9268292682927,
    "HouseOfUnits": 19344,
    "LandArea": 20.5,
    "Latitude": 42.3612999,
    "Longitude": -88.0899304,
    "NEBoundLatitude": 42.39806,
    "NEBoundLongitude": -88.0474079,
    "Population": 60002,
    "SWBoundLatitude": 42.293484,
    "SWBoungLongitude": -88.18529190000001,
    "State": "IL",
    "TotalWages": 1101138102.0,
    "WaterArea": 0.94,
    "Wealthy": 18351.689977000766,
    "Zipcode": "60073",
    "ZipcodeType": "Standard"
}
```

**Comment by veryxcit** [comment]
Hey not sure if you replied on github before you sent this. The zipcode is
found and returns fine, but then if I try to take the zipcode's Latitude
and Longitude co-ordinates and then try to find the nearby zipcodes, that's
the method that doesn't return results. So the search.by_coordinate returns
no results if using 60073's lat and long co-ordinates.

def bug(zip):

    search = ZipcodeSearchEngine()
    zipcode = search.by_zipcode(zip)
    print(zipcode)

    res = search.by_coordinate(zipcode.Latitude, zipcode.Longitude,
radius=20, returns=0)
    for r in res:
        print(r.Zipcode)

bug(20855) # try zip 20855
bug(60073) # try zip 60073

**Comment by MacHu-GWU** [comment]
Thank you, bug fixed. Please ``pip install --upgrade uszipcode``

**Comment by veryxcit** [comment]
Thank you!

*Alex Popa*   North Shore IT.me
[image: photo]
Main: 847-231-2123
Direct: 224-277-0699
Email: alex@nsit.me <alex@nsit.me>
Website: www.nsit.me <http://www.nsit.me/>

**Comment by MacHu-GWU** [comment]
I think it's fixed Please contact me if you found any bug.
