### ISSUE TITLE
Search by City/State returns Puerto Rico if City/State are None

### ISSUE THREAD

**Issue by ghost** [MacHu-GWU/uszipcode-project#20]
**Describe the bug**

Using a SearchEngine method "by_city_and_state" returns an unexpected result if one accidentally passes Nones. It can be handled by not doing this, obviously, but it makes sense I think to be consistent.

**To Reproduce**

```
ZIP_SEARCH_ENGINE = SearchEngine()

ZIP_SEARCH_ENGINE.by_city_and_state(None, None)
```
Output : 

`[Zipcode(zipcode_type='Standard', major_city='Adjuntas', post_office_city=None, common_city_list=['Adjuntas'] .... ..... ..... educational_attainment_for_population_25_and_over=None, school_enrollment_age_3_to_17=None)]`

**Expected behavior**

We should get a ZipCode object back that has None in every field, or simply None. However it appears default behavior of .by_zipcode() is to return a ZipCode object with all fields populated with Nones.

If we do this : 

`ZIP_SEARCH_ENGINE.by_zipcode(None)`

We get something like : 
`
Zipcode(zipcode_type=None, major_city=None, post_office_city=None  ..... ..... educational_attainment_for_population_25_and_over=None, school_enrollment_age_3_to_17=None)`

**Comment by MacHu-GWU** [comment]
Thank you for reporting, I will fix it shortly

**Comment by adam-attunely** [comment]
No worries, thanks for all your work on this module! It's really useful for research.
