### ISSUE TITLE
Location / URL to find definition of each variable?

### ISSUE THREAD

**Issue by windweller** [MacHu-GWU/uszipcode-project#22]
Hello,

I've been using this library and it has been quite amazing (simple to use and easy to get the data out). However, many of the detailed variables like `families_vs_singles` are left unexplained...I tried to look it up in the US Census main website but that has been difficult to navigate. Do you have a place to point us to if we are trying to find what these variables are/mean?

For example, does `Single_Guardian` under `families_vs_singles` mean single parent with children?

**Comment by MacHu-GWU** [comment]
@windweller you are right, Single_Guardian means only daddy or mom. I will add more document to describe the data point. Because the data is collected from a variety of trust source, I don't think there's an all in one website to describes everything.

**Comment by mamikonyana** [comment]
Hi @MacHu-GWU I am trying to extend this database (i.e. add more columns), but the code that creates the database is not in the codebase (I only found the old code under dataset/ directory), would you consider sharing the code as well?
