### ISSUE TITLE
missing lat and lng also missing results for radius after using "zipcode_type=None"

### ISSUE THREAD

**Issue by vinnieyao** [MacHu-GWU/uszipcode-project#24]
I used "zipcode_type=None" in by _zipcode, but I am still missing lat and lng data, like 01655.
I also used "zipcode_type=None" in by _coordinates, but I am still missing some zipcodes around the input zipcode. For example, 00715 should be the result of 00716 but it didn't.

Anyway, thank you for all of your work!

**Comment by jawinn** [comment]
@MacHu-GWU 
What about running the Google Maps API or some other lookup to update entries that are missing latitude and longitude in the dataset? It makes it hard to use this package for a search that compares distances when so many are missing (several hundred).

Example of some that are missing: 
29402 - Charleston, SC - PO Box only zip
94203 - Sacramento, CA - PO Box only zip

**Comment by MacHu-GWU** [comment]
@jawinn I ran a google map api for all the zipcode when I made the release, but I didn't run it everytime in new release. I do need some automation to build this database. But unfortunately, it is not available yet.
