### ISSUE TITLE
Possible to know sources of data

### ISSUE THREAD

**Issue by staplet14** [MacHu-GWU/uszipcode-project#25]
Would be great to know the data-sources, and year for the data. Particularly relevant when using this data to build/update machine learning models.

**Comment by LTMullineux** [comment]
I have the same issue, I need to know this for an academic report I'm putting together, would be great to know

**Comment by shsab** [comment]
I can see a resemblance between this data and ACS from census.gov. Is that the data source you are using? How can I get the updated information rather than 2015 one?

**Comment by MacHu-GWU** [comment]
@staplet14 @LTMullineux @shsab would you mind to send me an email, you can find it in __init__.py file. Thank you.
