### ISSUE TITLE
Some zipcode polygons are 3D lists

### ISSUE THREAD

**Issue by nog642** [MacHu-GWU/uszipcode-project#26]
The polygon for 44122 (using `simple_zipcode=False`) returns a 3D list, unlike most zipcodes. The regular 2D list is itself the only item in an outer list. The 2D list inside also seems much too short to be a good polygon for this zipcode.

I have `uszipcode==0.2.2` installed in a virtualenv.

```py
>>> search = SearchEngine(simple_zipcode=False)
>>> search.by_zipcode('44122').polygon
[[[-81.549838, 41.478182], [-81.549829, 41.474945], [-81.549883, 41.474739], [-81.550029, 41.474493], [-81.550482, 41.475187], [-81.550473, 41.477716], [-81.549838, 41.478182]]]
```

The expected behavior is that it returns a 2D list with many more points than that.

Other zipcodes I've found with the same issue (not a complete list):
* 31632
* 49426
* 45801
* 60605
* 22180
* 08540
* 01588
* 55901

**Comment by MacHu-GWU** [comment]
Thank you, I will check the data source I crawled for polygon and update it.
