### ISSUE TITLE
search.all() function is no longer available

### ISSUE THREAD

**Issue by jake381** [MacHu-GWU/uszipcode-project#27]
I have been using the search.all() function in a previous version of this code to loop over all zipcodes in the database. Is it still possible to access the list of all zipcodes? If not can this feature be added back in?
Thanks

**Comment by MacHu-GWU** [comment]
@jake381  I will add that back in. I recommend you to do ``search.query(zipcode_type=None, returns=999999)`` it is the equivalent method
