### ISSUE TITLE
documentation bug:  returns & the number of zips in chicago

### ISSUE THREAD

**Issue by notuntoward** [MacHu-GWU/uszipcode-project#28]
The documentation says that this:

```
# Looking for Chicago and IL, but entered wrong spelling.
>>> res = search.by_city_and_state("cicago", "il")
>>> len(res) # 56 zipcodes in Chicago
56
```

will print `56` at the end.  

However:

1.  It actually prints `5` because it's using the default value of `returns=5`
2.  If I supply `returns=5000`, so the number of zips isn't limited, the result is not `56` but `58`.

**Comment by MacHu-GWU** [comment]
Thank you I will look into it, you are right, I should have make it clear that returns is controls the limit

**Comment by MacHu-GWU** [comment]
@notuntoward  actually it is mentioned at https://uszipcode.readthedocs.io/01-Tutorial/index.html#restrict-number-of-results-to-return
