### ISSUE TITLE
Avoid saving the database on /tmp file

### ISSUE THREAD

**Issue by jlariza** [MacHu-GWU/uszipcode-project#29]
Saving the database on `/tmp` folder have several issues. The main one is that It forces you to download it every time the `/tmp` folder is cleared, like on a system reboot.

As well, it is generating issues when using it on a server that may use different users to run the shell and to run the app. When the downloading the file, `-rw-------` this permissions are attached to it, so only the owner may read it.

Why was the database moved from `~/.uszipcode/`?

Would it be possible to configure the database path, like #16 proposed? 

Thank you

**Comment by MacHu-GWU** [comment]
@jlariza I think its because the previous issue told me that the AWS Lambda and cloud container doesn't support to download file to $HOME directory. but allow to download to /tmp.

I will issue a new release that allows user to customize the path to download

**Comment by MacHu-GWU** [comment]
@jlariza I just released 0.2.4, now you can specify the directory you want to download the db file to. By default it is still ``$HOME/.uszipcode``

**Comment by jlariza** [comment]
Perfect. Thank you!
