### ISSUE TITLE
Cannot pip install into virtualenv with Python 2.7; AttributeError

### ISSUE THREAD

**Issue by smcoll** [MacHu-GWU/uszipcode-project#3]
```
$ pip install uszipcode
Collecting uszipcode
  Using cached uszipcode-0.0.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BZi9bp/uszipcode/setup.py", line 61, in <module>
        VERSION = __import__(NAME).__version__
      File "uszipcode/__init__.py", line 4, in <module>
        from .searchengine import ZipcodeSearchEngine
      File "uszipcode/searchengine.py", line 4, in <module>
        from uszipcode.data import (
      File "uszipcode/data/__init__.py", line 19, in <module>
        site.getsitepackages()[1], "uszipcode", "data", "zipcode.sqlite3")
    AttributeError: 'module' object has no attribute 'getsitepackages'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BZi9bp/uszipcode
```

**Comment by MacHu-GWU** [comment]
**Which version are you using? **

As far as I see, the ``site.getsitepackages`` method are new in Python2.7, if your are using Python2.6, I recommend:

1. unzip the source zip
2. edit uszipcode/data/__init__.py, line 19
3. change ``site.getsitepackages()[1]`` to ``r"C:\Python26\Lib\site-packages"``
4. copy uszipcode directory to ``C:\Python26\Lib\site-packages``

**Comment by smcoll** [comment]
i'm using 2.7.6.

**Comment by MacHu-GWU** [comment]
could you try::

    import site
    print site.getsitepackages()

see what happen

**Comment by smcoll** [comment]
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> print site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
>>> 
```

**Comment by MacHu-GWU** [comment]
Looks like your python are not installed correctly. Because site.getsitepackages is a Python27 standard lib. see this: https://docs.python.org/2/library/site.html#site.getsitepackages.

Looks like you are using linux, so I have two solution:

1. find a site.py for py2.7 on internet, for example from CPython official mirror site: https://github.com/python/cpython/blob/master/Lib/site.py
2. re-install py2.7

**Comment by smcoll** [comment]
OK, turns out that it's a known bug in `virtualenv`: https://github.com/pypa/virtualenv/issues/355

Unfortunately, this means that for some use cases, `uszipcode` is not a viable option...

**Comment by MacHu-GWU** [comment]
I think you can just hard code the sqlite database file path.

**Comment by MacHu-GWU** [comment]
@smcoll 

I recently made a stable release V 0.1.1. Now it's no longer using ``site.getsitepackages()`` to find the database file. It was bad supported for Linux and MacOS. Now I believe it's all fixed.

Thank you

**Comment by smcoll** [comment]
@MacHu-GWU confirmed as fixed.  Thank you.
