### ISSUE TITLE
Incomplete results using Search Engine 

### ISSUE THREAD

**Issue by UGuntupalli** [MacHu-GWU/uszipcode-project#37]
**Describe the bug**

The results of using the search engine with 2 different methods shown in the documentation yields incomplete results. I have used both the search.query() as well as search.by_state() 

**To Reproduce**

```python 
   from uszipcode import Zipcode 
   from uszipcode import SearchEngine 

   # Create a search engine object 
   search = SearchEngine() 
   # Get all the zip codes in the desired location 
   result = search.query(city="Long Island", state="NY") 
   
   # This yields a list of length 2. That is incorrect. Long Island has more zip codes than just 2 

   # Search using .by_state() method 
   res = search.by_state("New York")
   
   # This yields just 5 zip codes. Again, the state has more than 5 zip codes. It has 2,150 zip codes
```

**Expected behavior**

I would expect the package methods to list all the zip codes based on valid search criteria. If some are excluded, providing a brief explanation in the documentation on what kind of zip codes are excluded will be very helpful. 

**Screenshots**

 - Expected results for zip codes in long island 
![image](https://user-images.githubusercontent.com/47903157/84085135-c9dcc280-a999-11ea-86aa-9fb2dd491e6f.png) 

 - Expected results for zip codes in New York 
![image](https://user-images.githubusercontent.com/47903157/84085228-f98bca80-a999-11ea-9f81-08ce7d98da15.png)

 - Results from the code 
![image](https://user-images.githubusercontent.com/47903157/84085390-5a1b0780-a99a-11ea-95bd-d6fcd0b3758d.png)

![image](https://user-images.githubusercontent.com/47903157/84085419-6bfcaa80-a99a-11ea-9786-f6ccfa75dceb.png)

**Additional context**

**Comment by dvamossy** [comment]
> **Describe the bug**
> 
> The results of using the search engine with 2 different methods shown in the documentation yields incomplete results. I have used both the search.query() as well as search.by_state()
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> ```python
>    from uszipcode import Zipcode 
>    from uszipcode import SearchEngine 
> 
>    # Create a search engine object 
>    search = SearchEngine() 
>    # Get all the zip codes in the desired location 
>    result = search.query(city="Long Island", state="NY") 
>    
>    # This yields a list of length 2. That is incorrect. Long Island has more zip codes than just 2 
> 
>    # Search using .by_state() method 
>    res = search.by_state("New York")
>    
>    # This yields just 5 zip codes. Again, the state has more than 5 zip codes. It has 2,150 zip codes
> ```
> 
> **Expected behavior**
> 
> I would expect the package methods to list all the zip codes based on valid search criteria. If some are excluded, providing a brief explanation in the documentation on what kind of zip codes are excluded will be very helpful.
> 
> **Screenshots**
> 
> * Expected results for zip codes in long island
>   ![image](https://user-images.githubusercontent.com/47903157/84085135-c9dcc280-a999-11ea-86aa-9fb2dd491e6f.png)
> * Expected results for zip codes in New York
>   ![image](https://user-images.githubusercontent.com/47903157/84085228-f98bca80-a999-11ea-9f81-08ce7d98da15.png)
> * Results from the code
>   ![image](https://user-images.githubusercontent.com/47903157/84085390-5a1b0780-a99a-11ea-95bd-d6fcd0b3758d.png)
> 
> ![image](https://user-images.githubusercontent.com/47903157/84085419-6bfcaa80-a99a-11ea-9786-f6ccfa75dceb.png)
> 
> **Additional context**

you just have to change the default limit by adding returns=1000000 to your function call (a large number so that you will get all the data)

**Comment by MacHu-GWU** [comment]
@UGuntupalli https://uszipcode.readthedocs.io/01-Tutorial/index.html#restrict-number-of-results-to-return
