### ISSUE TITLE
Manassas Park, VA is included in Prince William County

### ISSUE THREAD

**Issue by EvanBolt** [MacHu-GWU/uszipcode-project#38]
**Describe the bug**

When requesting the zip code for Manassas Park, it is listed as being in Prince William County, but it is an independent city in VA and not part of any county

**To Reproduce**

`search = SearchEngine(simple_zipcode=True)`
`zipcode = zip_search_engine.by_zipcode('20111').to_dict()`

**Expected behavior**

Manassas Park should return as a county as well since it is an independent city.

**Comment by MacHu-GWU** [comment]
I cannot fix it on this level. But I do want to develop a way to improve single zipcode data error easily in next major release
