### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by berch** [MacHu-GWU/uszipcode-project#4]
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uszipcode
>>> search = uszipcode.ZipcodeSearchEngine()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/uszipcode/searchengine.py", line 106, in __init__
    self.connect = sqlite3.connect(DB_FILE)
sqlite3.OperationalError: unable to open database file
>>>

**Comment by MacHu-GWU** [comment]
Looks like it failed to get the correct database file path in Linux. I 'll fix it in next release.

**Comment by MacHu-GWU** [comment]
@berch 

I recently made a stable release V 0.1.1. It was bad supported for Linux and MacOS. Now I believe it's all fixed.

**Comment by berch** [comment]
It's fixed. Thanks.
