### ISSUE TITLE
Licensing issues from direct inclusion of dependencies

### ISSUE THREAD

**Issue by PeterJCLaw** [MacHu-GWU/uszipcode-project#41]
I've been evaluating using your package in a project with relatively strict licensing requirements. It looks initially like this project is really useful, however I spotted that you currently vendor in some dependencies (in [`uszipcode/pkg`](https://github.com/MacHu-GWU/uszipcode-project/tree/master/uszipcode/pkg)) rather than declaring them at the package level.

While I can see that one of them ([`sqlalchemy-mate`](https://pypi.org/project/sqlalchemy-mate/)) is another of your own packages and that [`haversine`](https://pypi.org/project/haversine/) is also licensed under MIT, the [`fuzzywuzzy`](https://pypi.org/project/fuzzywuzzy/) package appears to currently be licensed under GPLv2 and is thus incompatible with being distributed as part of an MIT-licensed distribution as this package does. The `fuzzywuzzy` package's license does appear to have changed (https://github.com/seatgeek/fuzzywuzzy/pull/131, https://github.com/seatgeek/fuzzywuzzy/commit/d079d6b8ed60f239756e15b9283009f1d442783a) from MIT to GPLv2 a few years ago, so perhaps the version you're embedding predates that?

If not, you may wish to review the licensing status of the packages to ensure that your package is compliant. At the very least please consider including in your README a mention of the packages which are being included and the licenses they're under.

**Comment by MacHu-GWU** [comment]
I see, because I am using pretty old fuzzywuzzy package. If the old fuzzywuzzy version I am using is MIT, what change I should made to adapt that? Any idea?

**Comment by PeterJCLaw** [comment]
Firstly: I am not a lawyer, so I cannot give legal advice. Please don't consider my input as such. I am also not an expert on software licensing.

Personally I would encourage that any project that embeds other projects at least mention it in their README (or somewhere else prominent) regardless of whether the other project's license strictly requires it; it's just a nice thing to do and ensures that consumers of the package can see clearly what's being used. (Dependencies which are pulled in via the `install_requires` field are already advertised there, but feel free to list them too if you like).

I would also encourage including a copy of the appropriate LICENSE file alongside the source code, as most license required that (include MIT), and (for convenience) a README or similar file which notes the upstream source of the package and the version used.

For `fuzzywuzzy` specifically I suggest also checking that the version you're embedding is the MIT licensed version (assuming that that is your intention). I'm concerned that it may not be because the included [`__init__.py`](https://github.com/MacHu-GWU/uszipcode-project/blob/53f37b9a6fd363c78ff16bab43738f87dff248ea/uszipcode/pkg/fuzzywuzzy/__init__.py) currently claims version 0.17.0, while the change from MIT to GPL.v2 happened [between 0.11.1 and 0.12.0](https://github.com/seatgeek/fuzzywuzzy/compare/0.11.1...0.12.0).

If instead you wish to use the latest (GPLv2 licensed) version of `fuzzywuzzy` and you want to continue to distribute a copy of it within this package then I think that means you'll need to license the _distribution_ of this package as GPLv2 as well. I believe it's OK to keep your code licensed as MIT in this case, however I don't know how you'd convey that in the Python package or on PyPI.

Alternatively, if you want to keep your package as being MIT licensed but still use the latest (GPLv2 licensed) version of `fuzzywuzzy` then you could instead have it as a dependency from PyPI (and remove it from the source tree and distribution package). I believe that this would allow you to continue to distribute your package as MIT licensed, while still using the latest `fuzzywuzzy` version.

Please again note that I am not a lawyer nor a license expert, so I cannot give legal advice. I can only tell you what I as developer tend to do when distributing packages.

**Comment by MacHu-GWU** [comment]
I figured it out. just remove the fuzzywuzzy source code from this project and use that as a dependency
