### ISSUE TITLE
sqlite to postgres

### ISSUE THREAD

**Issue by ra-esmith** [MacHu-GWU/uszipcode-project#44]
Hello, the documentation suggests

"(RECOMMEND) Dump the sqlite database to any relational database like Postgres, MySQL, and inject the database connection info in your application server."

Could you elaborate on what needs to be done ... to use postgres?

Not sure of what code changes one needs to make etc ...

Thanks!
Evan

**Comment by MacHu-GWU** [comment]
@ra-esmith I think this question is out of scope of this library. But I do can give you some solution:

1. find where you store the .sqlite file.
2. download dbeaver https://dbeaver.io/download/, it is a universal SQL client
3. connect to the sqlite database, do select * and dump the result as CSV
4. connect to your psql, and load from CSV

I am about to allow to use any private SQL database to host the data in next release. Then you just need 

```python

from uszipcode.pkg.sqlalchemy_mate import engine_creator
from uszipcode import SearchEngine

engine = engine_creator.create_postgresql(username, password, host, port, database)
se = SearchEngine(..., engine=engine)  
```

now it uses the psql and skip the sqlite db file download process
