### ISSUE TITLE
Import error using SQLAlchemy v1.4

### ISSUE THREAD

**Issue by jlariza** [MacHu-GWU/uszipcode-project#48]
uszipcode requires sqlalchemy as a dependency; but no version is specified so it will always install the latest version.

SQLAlchemy==1.4 was released yesterday. One of the changes is that 

```
from sqlalchemy.ext.declarative.api import DeclarativeMeta
```
used on `uszipcode-project/uszipcode/pkg/sqlalchemy_mate/pt.py` raises an import error. However, on uszipcode it is being ignored by a try except call.

So, a fresh install of uszipcode will produce a `ImportError: cannot import name 'SearchEngine'` when trying to import the SearchEngine.

**To Reproduce**

1. Create a fresh virtualenv
2. Run `pip install uszipcode`
3. Try to run `from uszipcode import SearchEngine` on the shell

**Expected behavior**

It should raise a versions error or something more telling; the try except being used on `uszipcode-project/uszipcode/pkg/sqlalchemy_mate/__init__.py` is reducing the obtained feedback and it may be confusing to new users.

Thank you,

**Comment by rv-krosenberg** [comment]
I am fairly new to Python and currently running into this issue. Is there a way to resolve this by downloading previous package versions of uszipcode or SQLALchemy?

**Comment by jlariza** [comment]
@rv-krosenberg you may run `pip install SQLAlchemy==1.3.23`  and use that SQLAlchemy version in your project

**Comment by povilasb** [comment]
Yeah, the requirement versions are not frozen: https://github.com/MacHu-GWU/uszipcode-project/blob/1b7681f8c8807badd8e6f5b409aca5b805d60dab/requirements.txt
Anybody cares to make a PR? :)

**Comment by aaronsmith1234** [comment]
Just wanted to add that I just ran into this issue as well.

**Comment by aaronsmith1234** [comment]
Hey all and @MacHu-GWU ,
I had some free time, so I went and fixed the breakage caused by SQLAlchemy 1.4.0. I don't have permission to push a branch here so had to fork the repo; commit with the necessary changes [here](https://github.com/aaronsmith1234/uszipcode-project/commit/73df0278f7232b789efa6621e629f8e50915bbef). Also note I pinned the SQLAlchemy version, but none of the other reqs. Not sure on best approach to figure out what the min required version is (decently new to Python still!)

**Comment by isik-kaplan** [comment]
Having the same issue here, tried bot the above 1.4.0, the 1.4.0 and 1.3.23 and all seem to fail, anyone care to give a hand with this one folks?

**Comment by aaronsmith1234** [comment]
@isik-kaplan, did you try my fix linked above?

**Comment by isik-kaplan** [comment]
@aaronsmith1234 haven't actually, let me install it from your repo and get back to you asap, thanks! 

Why haven't you submit a PR btw?

**Comment by aaronsmith1234** [comment]
Just a note, I just made sure that with those tweaks, all the tests were able to pass successfully; I’m using that as a proxy for actually working, assuming tests are covering that. 😬I’m still pretty new to GitHub, never done a pull request from a fork, I’ll take a look later tonight. Let me know if it works!

**Comment by aaronsmith1234** [comment]
Just opened PR #49 for this; easier to do than I imagined!

**Comment by kumarprakashmani** [comment]
Hi I was having a similar issue but I  fixed it by adding bold letter path in model .py file
"from .pkg.sqlalchemy_mate.**orm.extended_declarative_base** import ExtendedBase"

**Comment by kumarprakashmani** [comment]
> Having the same issue here, tried bot the above 1.4.0, the 1.4.0 and 1.3.23 and all seem to fail, anyone care to give a hand with this one folks?
Hi I was having a similar issue but I fixed it by adding bold letter path in model .py file can try this
"from .pkg.sqlalchemy_mate.orm.extended_declarative_base import ExtendedBase"

**Comment by isik-kaplan** [comment]
Hey, thanks! 

I actually deleted my containers and rebuilt them all and it magically fixed my issue with version pinned to 1.3.23, the version was pinned to 1.3.23 before rebuilding but somehow it didn't work without me rebuilding it.

**Comment by s22-rxr** [comment]
the requirements should be frozen.

**Comment by MacHu-GWU** [comment]
@aaronsmith1234 by the way, I made this compatible to sqlalchemy<1.4 as well by adding a try, catch around your code. Thank you for your contribution
