### ISSUE TITLE
Population update cycle and source for the population

### ISSUE THREAD

**Issue by darshil333** [MacHu-GWU/uszipcode-project#56]
Hello, thanks for this awesome tool.
I had question related to the population data. Is it using Census dataset (only) for the population count? and how often the population data is getting updated? when was the last time the population was updated? 
I tried to look into this by checking all the documentation and even issues but was little unclear. It would be great if you can help me on this!

**Comment by MacHu-GWU** [comment]
@darshil333  yes it is using Cencus dataset only for the population count, <=0.2.6 it is based on Cencus 2010 data, I just crawled 2020 Census data, plan to release new major version using Census 2020 data.

**Comment by MacHu-GWU** [comment]
@darshil333 just released a new version 1.0.1 and applied some Census 2020 data. And the data source are also attached.
