### ISSUE TITLE
Trying to import Zipcode from uszipcode is failing

### ISSUE THREAD

**Issue by pyDesi** [MacHu-GWU/uszipcode-project#59]
After successfully installing uszipcode, trying to import Zipcode is failing

#My Code
!pip install uszipcode
from uszipcode import Zipcode

This was working just fine for me about a month back on colab but is now consistently failing on my google colab

ImportError                               Traceback (most recent call last)
<ipython-input-2-5dded23d0ed2> in <module>()
      1 get_ipython().system('pip install uszipcode')
----> 2 from uszipcode import Zipcode

ImportError: cannot import name 'Zipcode' from 'uszipcode' (/usr/local/lib/python3.7/dist-packages/uszipcode/__init__.py)

**Comment by MacHu-GWU** [comment]
@pyDesi totally working in colab for me. maybe more information about your runtime?

![image](https://user-images.githubusercontent.com/6800411/150622977-a3a68ff3-a4a4-4a0d-98a3-6c6893ac0ce1.png)
