### ISSUE TITLE
How do you parse Common_city_list

### ISSUE THREAD

**Issue by 931743010** [MacHu-GWU/uszipcode-project#66]
Want to use
Data in simple_db.sqlite;
Export to Excel;
Common_city_list is displayed as eJyLVgouLSqqVIoFAA9dAyI=
How do you parse this data; Python is not very good; How do you parse this data using Java?

**Comment by MacHu-GWU** [comment]
Hi, it is just a base encoded pickle in Python. You could do this in Python:

```
import pickle
import base64

real_common_city_list = pickle.load(base64.b64decode(common_city_list.encode("utf-8")))
```
