### ISSUE TITLE
Incorrect/misleading zipcodes

### ISSUE THREAD

**Issue by jlshin** [MacHu-GWU/uszipcode-project#7]
I am looking at zip codes in the Southern California area and noticed a few lat/long coordinates that returned zip code that do not correspond to the zip code that google maps returns:

For example, when I look up 34.0352, -118.2583 via Google maps I get 90015, whereas the package returns 90079:

`search.by_coordinate(lng=-118.2583, lat=34.0352, radius=50, returns=1)`

>> [{"City": "Los Angeles", "Density": 0.0, "HouseOfUnits": 0, "LandArea": 0.01, "Latitude": 34.0405313, "Longitude": -118.25540320000002, "NEBoundLatitude": 34.041599, "NEBoundLongitude": -118.254093, "Population": 0, "SWBoundLatitude": 34.039571, "SWBoungLongitude": -118.256716, "State": "CA", "TotalWages": null, "WaterArea": 0.0, "Wealthy": null, "Zipcode": "90079", "ZipcodeType": "Standard"},
 {"City": "Los Angeles", "Density": 11102.923976608188, "HouseOfUnits": 8245, "LandArea": 1.71, "Latitude": 34.0390107, "Longitude": -118.2672801, "NEBoundLatitude": 34.053104, "NEBoundLongitude": -118.2492601, "Population": 18986, "SWBoundLatitude": 34.02588, "SWBoungLongitude": -118.28284599999999, "State": "CA", "TotalWages": 196952937.0, "WaterArea": 0.0, "Wealthy": 10373.587748867589, **"Zipcode": "90015",** "ZipcodeType": "Standard"}]

If I expand the `returns` variable to >1 then I do see that the correct zip code is in the second entry. 

Another example is 34.048, -118.2577, but this time it doesn't return the "correct" (according to Google maps) zip code until the 4th entry.

`search.by_coordinate(lng=-118.2577, lat=34.048, radius=50, returns=4)`
>> [{"City": "Los Angeles", "Density": 125.0, "HouseOfUnits": 0, "LandArea": 0.12, "Latitude": 34.052996, "Longitude": -118.2548551, "NEBoundLatitude": 34.056087, "NEBoundLongitude": -118.250157, "Population": 15, "SWBoundLatitude": 34.048743, "SWBoungLongitude": -118.259363, "State": "CA", "TotalWages": 75762361.0, "WaterArea": 0.0, "Wealthy": 5050824.066666666, "Zipcode": "90071", "ZipcodeType": "Standard"},
 {"City": "Los Angeles", "Density": 25017.857142857138, "HouseOfUnits": 4990, "LandArea": 0.28, "Latitude": 34.0434783, "Longitude": -118.2519314, "NEBoundLatitude": 34.050176, "NEBoundLongitude": -118.24524, "Population": 7005, "SWBoundLatitude": 34.037303, "SWBoungLongitude": -118.257926, "State": "CA", "TotalWages": 91984035.0, "WaterArea": 0.0, "Wealthy": 13131.197002141329, "Zipcode": "90014", "ZipcodeType": "Standard"},
 {"City": "Los Angeles", "Density": 0.0, "HouseOfUnits": 0, "LandArea": 0.01, "Latitude": 34.0405313, "Longitude": -118.25540320000002, "NEBoundLatitude": 34.041599, "NEBoundLongitude": -118.254093, "Population": 0, "SWBoundLatitude": 34.039571, "SWBoungLongitude": -118.256716, "State": "CA", "TotalWages": null, "WaterArea": 0.0, "Wealthy": null, "Zipcode": "90079", "ZipcodeType": "Standard"},
 {"City": "Los Angeles", "Density": 32558.90410958904, "HouseOfUnits": 10610, "LandArea": 0.73, "Latitude": 34.054379700000005, "Longitude": -118.2672801, "NEBoundLatitude": 34.060871, "NEBoundLongitude": -118.2541801, "Population": 23768, "SWBoundLatitude": 34.043726899999996, "SWBoungLongitude": -118.27431299999999, "State": "CA", "TotalWages": 229419093.0, "WaterArea": 0.0, "Wealthy": 9652.435753954898, **"Zipcode": "90017"**, "ZipcodeType": "Standard"}]

**Comment by MacHu-GWU** [comment]
Thank you for reporting the bugs. I will use more up - to - date database in next release

**Comment by MacHu-GWU** [comment]
It is fixed in 0.2.0 by using more up-to-date database
