### ISSUE TITLE
sqlalchemy >= 2.0.0 causes bug

### ISSUE THREAD

**Issue by gravesee** [MacHu-GWU/uszipcode-project#72]
Had to install sqlalchemy < 2.0.0 for this package to work.

**Comment by MacHu-GWU** [comment]
Yes, because sqlalchemy 1.X and 2.X use incompatible API. I cannot predict `uszipcode` user would use 1.X or 2.X, which will be too much work to adapt both API.

**Comment by gravesee** [comment]
Sorry, I'm just suggesting that the requirements.txt use <= 2.0.0 for that dependency instead of >1.4.0
