### ISSUE TITLE
Zipcodes are out of date

### ISSUE THREAD

**Issue by jake-kent** [MacHu-GWU/uszipcode-project#8]
The zip code database you are using is from 2012. Many places (Brooklyn zip codes in the 11200-11300 range for example) have added or changed zip codes since then, making this zip code data invalid/unusable. Please update the zip code database you are using to be more up to date.

**Comment by MacHu-GWU** [comment]
Thank you for reminding, I will use more up-to-date db in next release

**Comment by jake-kent** [comment]
Much appreciated. How soon might you be able to have another release out by?

**Comment by MacHu-GWU** [comment]
I think it takes another two week. Because currently I can't got good quality zipcode data except from the 2010 censors. I recently find a good one with even more useful data points https://www.unitedstateszipcodes.org/, but it takes time to crawl. I am thinking that, how's the non-existing zipcode in my database bother you? Maybe if I know your use case, I can provide you a temp and future compatible solution

**Comment by jake-kent** [comment]
Great! Thank you! We were running into an issue for checking the state (which should be New York) for newly created zip codes in the 11200-11300 range that aren't represented in the db. We have added special handling to our code in the meantime. Just having an updated db (https://www.unitedstateszipcodes.org/ has the new zip codes in the 11200-11300 range) will be all we need to solve the issue.

**Comment by rqblast** [comment]
@MacHu-GWU  I've checked the current version with the following source: http://download.geonames.org/export/zip/
And there is about 11k postal codes which are not represented in the library.
Perhaps, you can use this source?

**Comment by MacHu-GWU** [comment]
@rqblast http://download.geonames.org/export/zip/ this one doesn't looks like us zipcode, example: `CA	T0A	Eastern Alberta (St. Paul)	Alberta	AB					54.766	-111.7174	`, and there's no other information like Population, Financial.

**Comment by Yum1ng** [comment]
These zipcodes (San Diego, CA) are missing from the dataset. 
92136
92182
92132
92100
92067
92052
92140
92093
92060
92158
92161
92023
91931
92935
92145
92049
91947
92112
92015
91951
92143
91940
91909
92072
92079
93633

**Comment by gone** [comment]
Did an updated release end up going out?

**Comment by Quetzalcohuatl** [comment]
These zipcodes are also missing:

 [1] 61324 60029 61132 60474 10125 45354 44068 44250 45319 43010 45319 44265 43547 17016 19523 19523 19523 19523 19523
 [20] 19523 18335 17016  1262  1083  1350  1262  1009  1074  1262  1092  1083  1262  1262  1092  1083  1092  1350  2712
 [39]  1262  1262  1467  1083  1244  1092  1092  1083  1350 12915 14707 14707 12927 12915 12915 12927 13404 12820 12915
 [58] 12915 13615 12820 12915 13615 13615 32163 14785 13305 12856 13305 12177 13115 12915 13615 14785 14707 14707 14539
 [77] 14539 13426 12975 12929 14169 14169 14854 13139 12933 14168 14827 14827 14856 14588 14588 14827 14827 14876 14876
 [96] 13139 12778 13102 10988 10988 10988 10988 10949 16246 16246 15754 15745 16512 15716 15716 16684 16684 16663 16677
[115] 16328 18813 16352 18626 18814 16344 18625 18454 16843 16873 16631 15737 16328 16843 16211 16328 16161 16140 16132
[134] 16140 17760 14745 14745  1029  1093  1029  1029

**Comment by MacHu-GWU** [comment]
@gone I am trying to integrate the data in https://www.unitedstateszipcodes.org/ with ``uszipcode``. The new release is still in development.

**Comment by MacHu-GWU** [comment]
@Quetzalcohuatl Thank you for your information, I will add these in next release.

**Comment by MacHu-GWU** [comment]
@Yum1ng Thank you for letting me know, I will add those in the next release. By the way, what is your data source of these missing zipcode?

**Comment by MacHu-GWU** [comment]
@Yum1ng @Quetzalcohuatl @gone @jake-kent 

Hi Everyone, I have done the database upgrade. Now you can even have access to real estate, education, race, age data like what you see https://www.unitedstateszipcodes.org/10001/.

But, the database size growth to 450MB... Anyone has suggestion about how to host the data?

**Comment by MacHu-GWU** [comment]
Now the backend database is hosted on https://datahub.io/machu-gwu.

And a new release is released, please note, since the database is greatly improved, the API for 0.2.x is not compatible with 0.1.x.
